"""tools/docs/extractor.py — structured extraction from docs/src/.

Builds two machine-readable outputs every downstream consumer needs:

1. ``schema/glossary.yml`` — structured glossary (term, acronym, EN / FR
   definitions, cross-references). Drives the inline-help hover cards
   (#670) and the drift check's acronym-coverage gate (#672).

2. ``schema/sections.yml`` — per-section metadata: source path, title,
   slug, language, anchor. Drives the SPA tab → help-fragment mapping.

Both files are regenerated on every ``tools/docs/build.py`` run so the
drift rule is "edit the source, rerun the build." No human curation.
"""
from __future__ import annotations

import logging
import re
from pathlib import Path

import yaml

log = logging.getLogger('slyled.docs.extractor')

ROOT = Path(__file__).resolve().parent.parent.parent
SRC = ROOT / 'docs' / 'src'
SCHEMA = ROOT / 'docs' / 'schema'

# Glossary table row: "| **Term** | Acronym | Definition | See-also |".
GLOSSARY_ROW = re.compile(
    r'^\|\s*\*\*([^*]+)\*\*\s*\|\s*([^|]*?)\s*\|\s*([^|]*?)\s*\|\s*([^|]*?)\s*\|\s*$'
)


def parse_glossary(md_path: Path) -> list[dict]:
    """Pull all glossary rows from ``20-glossary.md``.

    Returns list of dicts ready to serialise as YAML:

        [{term, acronym, short (None), long, see_also}, ...]
    """
    if not md_path.exists():
        return []
    entries = []
    for raw in md_path.read_text(encoding='utf-8', errors='replace').splitlines():
        m = GLOSSARY_ROW.match(raw)
        if not m:
            continue
        term, acronym, defn, see_also = (s.strip() for s in m.groups())
        # Skip the header row ("| Term | Acronym | ... |") and divider rows.
        if term.lower() in {'term', '—'} and defn.lower() in {'definition', '—'}:
            continue
        if acronym in {'—', '-', ''}:
            acronym_val = None
        else:
            acronym_val = acronym
        entries.append({
            'term': term,
            'acronym': acronym_val,
            'long': defn,
            'see_also': [s.strip() for s in re.split(r'[;,]', see_also) if s.strip()],
        })
    return entries


def parse_sections(lang: str) -> list[dict]:
    """Collect section metadata from every ``docs/src/<lang>/*.md``."""
    out = []
    for md in sorted((SRC / lang).glob('*.md')):
        title = md.stem
        for line in md.read_text(encoding='utf-8', errors='replace').splitlines():
            if line.startswith('## '):
                title = line[3:].strip()
                break
            if line.startswith('# '):
                title = line[2:].strip()
                break
        out.append({
            'slug': md.stem,
            'file': str(md.relative_to(ROOT).as_posix()),
            'title': title,
            'lang': lang,
            'fragment': f'docs/build/{lang}/help/{md.stem}.html',
        })
    return out


def build_schema():
    """Write the canonical glossary + sections YAMLs. Merges EN + FR."""
    SCHEMA.mkdir(parents=True, exist_ok=True)

    en_glossary = parse_glossary(SRC / 'en' / '20-glossary.md')
    fr_glossary = parse_glossary(SRC / 'fr' / '20-glossary.md')
    fr_by_term = {e['term']: e for e in fr_glossary}
    merged = []
    for e in en_glossary:
        fr = fr_by_term.get(e['term'], {})
        merged.append({
            'term': e['term'],
            'acronym': bool(e['acronym']),
            'en': {
                'short': e['acronym'] if e['acronym'] else None,
                'long':  e['long'],
            },
            'fr': {
                'short': fr.get('acronym'),
                'long':  fr.get('long'),
            },
            'see_also': e['see_also'],
        })

    glossary_path = SCHEMA / 'glossary.yml'
    glossary_path.write_text(
        '# Generated by tools/docs/extractor.py — do not edit by hand.\n'
        '# Edit docs/src/en/20-glossary.md (and fr/) then rerun build.py.\n\n'
        + yaml.safe_dump(merged, sort_keys=False, allow_unicode=True),
        encoding='utf-8')
    log.info('glossary: %d entries → %s', len(merged),
             glossary_path.relative_to(ROOT))

    sections = {'en': parse_sections('en'), 'fr': parse_sections('fr')}
    sections_path = SCHEMA / 'sections.yml'
    sections_path.write_text(
        '# Generated by tools/docs/extractor.py — do not edit by hand.\n'
        + yaml.safe_dump(sections, sort_keys=False, allow_unicode=True),
        encoding='utf-8')
    log.info('sections: EN=%d FR=%d → %s',
             len(sections['en']), len(sections['fr']),
             sections_path.relative_to(ROOT))


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO,
                        format='%(levelname)s %(name)s: %(message)s')
    build_schema()
