/*
 * DmxBridge.cpp — DMX-512 output via ESP32 UART2 + RS-485 transceiver.
 *
 * DMX-512 frame format:
 *   BREAK  (≥88μs low)
 *   MAB    (≥8μs high / mark-after-break)
 *   START  (0x00 start code, 8N2)
 *   DATA   (1-512 channel bytes, 8N2)
 *
 * The ESP32 UART2 is configured at 250kbaud, 8N2.
 * Break/MAB are generated by toggling the TX pin manually.
 */

#include "DmxBridge.h"

#ifdef BOARD_DMX_BRIDGE

#include <Preferences.h>

// ── Globals ──────────────────────────────────────────────────────────────────

DmxBridgeConfig dmxCfg;
uint8_t dmxBuf[DMX_UNIVERSE_MAX + 1]; // [0] = start code, [1..512] = channels
CRGB leds[NUM_LEDS];                  // virtual LED array for action rendering

static HardwareSerial DmxSerial(2);   // UART2

// ── NVS persistence ──────────────────────────────────────────────────────────

static const char* NVS_NS = "slydmx";

void dmxLoadConfig() {
  Preferences prefs;
  prefs.begin(NVS_NS, true);
  dmxCfg.universe           = prefs.getUShort("universe", 0);
  dmxCfg.startAddress       = prefs.getUShort("startAddr", 1);
  dmxCfg.channelsPerFixture = prefs.getUChar("chPerFix", 3);
  dmxCfg.fixtureCount       = prefs.getUChar("fixCount", 1);
  prefs.end();
}

void dmxSaveConfig() {
  Preferences prefs;
  prefs.begin(NVS_NS, false);
  prefs.putUShort("universe", dmxCfg.universe);
  prefs.putUShort("startAddr", dmxCfg.startAddress);
  prefs.putUChar("chPerFix", dmxCfg.channelsPerFixture);
  prefs.putUChar("fixCount", dmxCfg.fixtureCount);
  prefs.end();
}

// ── DMX-512 UART init ────────────────────────────────────────────────────────

void dmxInit() {
  memset(dmxBuf, 0, sizeof(dmxBuf));
  memset(leds, 0, sizeof(leds));

  // Load config from NVS
  dmxLoadConfig();
  if (dmxCfg.startAddress < 1) dmxCfg.startAddress = 1;
  if (dmxCfg.channelsPerFixture < 1) dmxCfg.channelsPerFixture = 3;
  if (dmxCfg.fixtureCount < 1) dmxCfg.fixtureCount = 1;

  // RS-485 direction enable pin (HIGH = transmit)
  pinMode(DMX_EN_PIN, OUTPUT);
  digitalWrite(DMX_EN_PIN, HIGH);

  // Configure UART2 for DMX: 250kbaud, 8N2
  DmxSerial.begin(DMX_BAUD, SERIAL_8N2, -1, DMX_TX_PIN);

  if (Serial) {
    Serial.print(F("[DMX] Init: universe="));
    Serial.print(dmxCfg.universe);
    Serial.print(F(" addr="));
    Serial.print(dmxCfg.startAddress);
    Serial.print(F(" ch/fix="));
    Serial.print(dmxCfg.channelsPerFixture);
    Serial.print(F(" fixtures="));
    Serial.println(dmxCfg.fixtureCount);
  }
}

// ── DMX-512 frame output ─────────────────────────────────────────────────────

void dmxSendFrame() {
  // Generate BREAK by driving TX pin low for ≥88μs
  DmxSerial.end();
  pinMode(DMX_TX_PIN, OUTPUT);
  digitalWrite(DMX_TX_PIN, LOW);
  delayMicroseconds(120);  // BREAK: 120μs

  // MAB: TX high for ≥8μs
  digitalWrite(DMX_TX_PIN, HIGH);
  delayMicroseconds(12);   // MAB: 12μs

  // Re-init UART and send frame
  DmxSerial.begin(DMX_BAUD, SERIAL_8N2, -1, DMX_TX_PIN);

  // Send start code + all 512 channels
  DmxSerial.write(dmxBuf, DMX_UNIVERSE_MAX + 1);
  DmxSerial.flush();
}

// ── Copy virtual leds[] to DMX channel buffer ────────────────────────────────

void dmxUpdateFromLeds() {
  uint16_t addr = dmxCfg.startAddress; // 1-based DMX address
  uint8_t cpf = dmxCfg.channelsPerFixture;
  uint16_t maxFix = dmxCfg.fixtureCount;
  if (maxFix > NUM_LEDS) maxFix = NUM_LEDS;

  for (uint16_t i = 0; i < maxFix; i++) {
    uint16_t slot = addr + (uint16_t)i * cpf;
    if (slot > DMX_UNIVERSE_MAX) break;

    // Map CRGB → DMX channels at the fixture's address
    if (cpf >= 1 && slot <= DMX_UNIVERSE_MAX) dmxBuf[slot]     = leds[i].r;
    if (cpf >= 2 && slot + 1 <= DMX_UNIVERSE_MAX) dmxBuf[slot + 1] = leds[i].g;
    if (cpf >= 3 && slot + 2 <= DMX_UNIVERSE_MAX) dmxBuf[slot + 2] = leds[i].b;
    if (cpf >= 4 && slot + 3 <= DMX_UNIVERSE_MAX) dmxBuf[slot + 3] = 255; // dimmer full
  }
}

// ── Helpers for BOARD_CHILD compatibility ─────────────────────────────────

void clearAndShow() {
  memset(leds, 0, sizeof(CRGB) * NUM_LEDS);
  memset(dmxBuf, 0, sizeof(dmxBuf));
  dmxSendFrame();
}

void fill_solid(CRGB* arr, uint16_t count, CRGB color) {
  for (uint16_t i = 0; i < count; i++) arr[i] = color;
}

#endif // BOARD_DMX_BRIDGE
